server:
  port: ${PORT:7071}
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_REPOSITORY_URL:https://github.com/SDSACT/coe-configurations.git}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost}:${EUREKA_SERVER_PORT:7070}/eureka/
    enabled: true
---
spring:
  profiles: stage-config1
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_REPOSITORY_URL:file://cesutil/config/config-repo}
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA1_SERVER_URL}:${EUREKA1_SERVER_PORT:7070}/eureka/,${EUREKA2_SERVER_URL}:${EUREKA2_SERVER_PORT:7070}/eureka/
---
spring:
  profiles: stage-config2
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_REPOSITORY_URL:file://cesutil/config/config-repo}
eureka:
  client:
    serviceUrl:
      defaultZone:  ${EUREKA1_SERVER_URL}:${EUREKA1_SERVER_PORT:7070}/eureka/,${EUREKA2_SERVER_URL}:${EUREKA2_SERVER_PORT:7070}/eureka/
---
